const fs = require('fs');
const path = require('path');

// Read the environment variable passed via cross-env
const ENV_VALUE = process.env.NODE_ENV || 'production';

// Path to JS file to generate
const envFilePath = path.join(__dirname, '..', 'config', 'config.ts');

// JS content to write
const fileContent = `/* This file is auto-generated by scripts/generate-config.js */
// Do not edit this file directly.
type ENV = 'development' | 'production';
const env = '${ENV_VALUE}';
const environment: ENV = env  ? env : 'production';
// if (environment === 'development') {
// 	console.log('Running in development mode');
// 	console.log(process.env)
// } else {
// 	console.log('Running in production mode');
// 	console.log(process.env)
// }
interface IEnvConfig {
	appName: string;
	version: string;
	baseUrl: string;
	documentationUrl: string;
	displayName: string;
}
type IConfig = Record<ENV, IEnvConfig>;
// Environment-specific settings
const config: IConfig = {
	development: {
		appName: 'PDF4me Dev',
		version: '1.0.4',
		baseUrl: 'https://api-dev.pdf4me.com',
		documentationUrl: 'https://dev.pdf4me.com/apiv2/documentation/',
		displayName: 'PDF4ME DEV API',
	},
	production: {
		appName: 'PDF4me',
		displayName: 'PDF4ME API',
		version: '1.4.0',
		baseUrl: 'https://api.pdf4me.com',
		documentationUrl: 'https://dev.pdf4me.com/apiv2/documentation/',
	},
};

// Export final config
export default {
	...config[environment],
	ENV: environment,
};

`;

// Ensure directory exists
fs.mkdirSync(path.dirname(envFilePath), { recursive: true });

// If file exists, remove it first
if (fs.existsSync(envFilePath)) {
  fs.unlinkSync(envFilePath);
  console.log('Previous config.ts removed');
}


// Write the file
fs.writeFileSync(envFilePath, fileContent);

console.log(`Generated config.ts with ENV='${ENV_VALUE}'`);
